### ISSUE TITLE
The type initializer for 'Dice.Roller' threw an exception.

### ISSUE THREAD

**Issue by dinolick** [skizzerz/DiceRoller#1]
Hello! I'm trying out DiceRoller and can't seem to get it to work.
**Framework**: 4.6.1
**Version**: 3.0.1

This is how I'm using it: 

`try`
`                {`
`                    var result = Roller.Roll("1d6");`
`                    await message.Channel.SendMessageAsync("You rolled an: `" + result + "`");`
`                }`
`                catch (Exception ex)`
`                {`
`                    await message.Channel.SendMessageAsync(ex.Message);`
`                }`

However I get a generic exception with the message "The type initializer for 'Dice.Roller' threw an exception."

**Comment by skizzerz** [comment]
Hi, thanks for the report. Can you confirm that you installed DiceRoller via the NuGet package?

If so, having additional details on the exception would be helpful, specifically what exception the type initializer threw. I'm having difficulty reproducing this on my own test setup.

**Comment by dinolick** [comment]
Thanks for the reply, yes I installed via `install-Package DiceRoller` and added all the dependencies.
This is the only info the exception prints out unfortunately as is

`exception.HResult` prints out "-2146233036"
`exception.InnerException.Message` prints out the following:
"Could not load file or assembly 'System.ValueTuple, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)"

**Comment by skizzerz** [comment]
It looks like your version of System.ValueTuple is out of date. Ensure that you have version 4.3 or higher of System.ValueTuple installed via `Install-Package System.ValueTuple -Version 4.3.1` or `Install-Package System.ValueTuple -Version 4.4.0` (or via the Updates tab in Visual Studio's NuGet Package Manager). Since you are on .NET Framework 4.6.1, you should have no issues using System.ValueTuple 4.4.0, but if that's still failing then try downgrading to System.ValueTuple 4.3.1.

Not sure why installing DiceRoller didn't do that, to be honest.

**Comment by skizzerz** [comment]
(And if that doesn't work then there might be something on my end that I just noticed, so let me know)

**Comment by dinolick** [comment]
`Install-Package System.ValueTuple -Version 4.4.0` worked for me. I let it install whichever one it defaulted to when requested by DiceRoller. It is functioning now. Sorry! c:

**Comment by skizzerz** [comment]
I'll push out a version 3.0.2 which will fix it pulling in outdated dependencies in the nearish future.
