### ISSUE TITLE
Incorrect Parse

### ISSUE THREAD

**Issue by IDM3** [skizzerz/DiceRoller#10]
When using syntax similar to "1d20-1", it parses it to 1d20.success-1, instead of parsing to math as would be expected, checked the dice expression documentation and it seems to be an issue.

**Comment by skizzerz** [comment]
I'm unable to reproduce this issue on the latest release. What specific roll were you using to encounter this issue?

If you are using the latest code from the master branch, don't (unless you are explicitly testing future library versions for regression, in which case do and thanks!). Alpha versions are unstable and the current codebase is broken in quite a few ways. Only install via NuGet or a release tag.

**Comment by skizzerz** [comment]
Was able to reproduce on the latest alpha version and implemented a fix, as well as some tests to catch it should it come up again. To recap what I said earlier (since it wasn't entirely clear)

- For all production uses of this library, stick to stable releases (via NuGet or release tags). The latest version found in the master branch is not guaranteed to be stable, and right now there are a handful of known bugs with it.
- Use the master branch only for testing the library itself or for testing library changes in a test/alpha branch of your codebase. If doing the latter, expect that the API is not stable and may cause breaking changes between commits.

In either case, it's helpful to report which version you encountered the bug on :)

**Comment by IDM3** [comment]
will do in the future thanks (For the record, yeah I forked the repository and added it instead of nuget in an effort to try and help contribute, since I found the library useful, I'm just using it for a discord bot, to help with a server I'm running.  I reverted it back to the release tag)
