### ISSUE TITLE
Bugs in D&D Beyond's implementation of DiceRoller (Part one)

### ISSUE THREAD

**Issue by cbaer9** [skizzerz/DiceRoller#14]
D&D Beyond uses DiceRoller in their forums (for play-by-post D&D, etc.) But, for years, the forum has been plagued by intermittent dice roller bugs. We'd love your help in trying to figure out what's going on!

The bugs appear in a number of different flavors, but here's perhaps the most common one:  
Mouseovers give nonsensical and contradictory results, or just an endlessly spinning ball.

Here's one example: [https://www.dndbeyond.com/forums/d-d-beyond-general/play-by-post/54005-ghosts-of-saltmarsh-cbaer8-campaign-thread?comment=8589](https://www.dndbeyond.com/forums/d-d-beyond-general/play-by-post/54005-ghosts-of-saltmarsh-cbaer8-campaign-thread?comment=8589) 

The first roll in that post was a simple 1d20+x roll resulting in an 18, but the mouseover suggests a pretty complex syntax roll resulting in a 9.

<img width="729" alt="Screenshot 2023-08-20 at 11 34 15 AM" src="https://github.com/skizzerz/DiceRoller/assets/17763215/d2872ea9-8432-416b-9e41-4285fc7c4ae4">

Also, on the same page, you can see just how many "potentially manipulated dice roll results" banners there are. While occasionally one can expect to accidentally trigger a banner by editing a post too close to a roll, most of these posts were never edited at all. 

Can you make anything of this?
Thanks so much!

**Comment by skizzerz** [comment]
That complicated expression is a damage roll, which seems a bit odd as there aren't any damage rolls in that post. In any case, it seems like this isn't an issue with this particular library. The tooltips aren't part of this code at all, but it seems like they might be fetching the wrong post/roll? That's my initial impression at least, from looking at the generated HTML code of the post.

The expression is saying "If the previous roll in this post was not a crit (aka not a natural 20), roll 1d8+4, otherwise roll 2d8+4". That expression is automatically generated when using the "Combat" option in the dice roller toolbar icon (also not part of this library, but I did have a hand in making that as well).

Going to close this out as this isn't an issue with this code, but you can forward the above analysis to the D&D Beyond devs to help them figure out what might be happening here.
