### ISSUE TITLE
min-max

### ISSUE THREAD

**Issue by spindisc** [skizzerz/DiceRoller#3]
In my game I would like to present weapon damage in a classic D&D format, that is if the weapon damage is say 2d6+2 i would like to present that as (4-14). But I cannot find any functions that returns the minimum and the maximum result a die roll could yield. Have I missed something, or is this not implemented?

**Comment by skizzerz** [comment]
There's nothing like that built-in, but you can emulate it by creating some custom `RollerConfig`s:

```cs
var roll = "2d6+2";

var rollMinConfig = new RollerConfig()
{
    GetRandomBytes = arr => BitConverter.GetBytes(0).CopyTo(arr, 0),
    NormalSidesOnly = true
};

var rollMaxConfig = new RollerConfig()
{
    GetRandomBytes = arr => BitConverter.GetBytes(29999).CopyTo(arr, 0),
    NormalSidesOnly = true
};

var minResult = Roller.Roll(roll, rollMinConfig);
var maxResult = Roller.Roll(roll, rollMaxConfig);

return $"{minResult.Value}-{maxResult.Value}";
```

Basically, you replace the built-in RNG with one that always returns the same result. In the first case (rollMinConfig) you always return a roll of 0 (which equates to rolling 1 on every die). In the second case, you always return a roll of 29,999 (which equates to rolling the max on d2, d3, d4, d6, d8, d10, d12, d20, d100, d1000, or d10000 -- it does not necessarily equate to the max on other dice types). In order to ensure that the max is actually the max, I also block rolling non-standard dice like d19.

If you want to support more dice types, the max should be the least common multiple of all dice types you support minus 1. See https://skizzerz.net/DiceRoller/Dice/RollerConfig/GetRandomBytes for more details.

**Comment by skizzerz** [comment]
Took forever (sorry), but `Roller.Min()`, `Roller.Max()`, and `Roller.Average()` now exist and can be used to achieve this much more easily and with arbitrary die sizes.
