### ISSUE TITLE
Cyberpunk Red Style Explode Once, Implode Once rolls. (or Compound Once/Collapse Once)

### ISSUE THREAD

**Issue by sprunka** [skizzerz/DiceRoller#9]
I use a VTT that uses this library (Mythic Table). So far, I have not found in the documentation for this library any method for triggering this type of roll.
I've also tried using my own "if()" syntax, but the Mythic Table incorporation of this library doesn't seem to support it, or I just haven't gotten my "if()" right yet.

This might be 2 or more Feature requests:
1) Please include a "once" option to existing methods for explode() and compound() (and implode/collapse)
2) Please include an implode() method (and a collapse() method?)

Thank you!

**Comment by skizzerz** [comment]
I’m not familiar with Cyberpunk Red, can you please explain the game mechanics for these particular roll types so I have a better idea what you’re asking for?

**Comment by sprunka** [comment]
Sure!
Roll 1d10 _(+ skill_base)_
1. if it is a 10, re-roll and add /explode_once(=10)/ (compound or explode logic could be used here -- potentially, add the "once" feature to both methods?)
2. if it is a 1, re-roll and subtract /implode_once(=10)/ (implode would deduct the value of a second roll the same way explode() adds while collapse would deduct the same way compound() adds.)
Example rolls:
1d10 (result 4) _(+ 14 skill)_ = 18 total
1d10 (result 10) **+** second 1d10 (result 4) _(+ 14 skill)_ = 28 total
1d10 (result 1) **-** second 1d10 (result 5) _(+ 14 skill)_ = 10 total

Most dice rolling systems will use implode and explode, but since only the total is of concern in CP, compound and collapse would result in the same overall sum.

**Comment by ryantheleach** [comment]
Are there any other dice rollers / vtt systems that already support this type of roll? What syntax/grammar do they use to implement the dice rolls?

**Comment by sprunka** [comment]
The first app that comes to mind is an older Android App (QuickDiceRoller): They use one function for Explode and Collapse together: exp(XdY, eN, iN, limitE, limitI) http://www.ohmnibus.net/wiki/index.php?n=Qdr.Exp
DiceMaiden for Discord uses XdY eN for explode_once and XdY ieN for explode forever. They don't have an implode/collapse.
I think Roll20's character sheet template has a long-code way of doing it, but nothing natively.
I believe FoundryVTT has it built into the character sheet as well, but does include the explode once option like this: /roll XdYxoN in its core dice machine.
I don't see anything for an implode or collapse.

**Comment by skizzerz** [comment]
I'm getting ready to look into this and wanted feedback on the proposed syntax for these:

- **Explode once:** `!eo` / `.explodeOnce()` -- `1d10!eo` will explode once when a 10 is rolled (alternative ways to specify the same roll would be `1d10!eo10`, `1d10!eo=10`, and `1d10.explodeOnce(=10)`)
- **Implode:** `!i` / `.implode()`
- **Implode once:** `!io` / `.implodeOnce()`
- **Compound implode:** `.compoundImplode()` (similar to compound penetrate this would not have a shorthand)

Would having "once" versions for the various compounds be useful as well? Please note that the end result is the same for regular explode vs compound, the difference is how the die is represented in the full result. With explode, there will be multiple dice in the final result, whereas with compound there will be a single die in the final result containing the total.

I'm hesitant on using the term "collapse" because it could be seen as the inverse of "expand" rather than the inverse of "compound."

**Comment by sprunka** [comment]
Syntax: That's perfect, IMO.
I haven't used compound or it's inverse in any system. I've always seen it as explode and implode... a second die is added (or subtracted) from the total.
I would imagine that if there is a demand for compound that compoundOnce makes perfect sense.
LIkewise, as implode is to explode so to does it make sense to do a compoundImplode() also for the "once" type.

Thank you so much for working on it!
